import React from 'react'
import Head from 'next/head'
import CookieStandHeader from './Header'
import CookieStandForm from './Main'
import Footer from './Footer'
import { useState } from 'react'

const CookieStandAdmin = () => {
    const [branches,setBranches] = useState('0')
    return (
        <div>
        <Head>
          <title>Cookie Stand Admin</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>  
  
        <CookieStandHeader/>
        
        <CookieStandForm setBranches={setBranches}/>
        <Footer branches={branches}/>
      </div>
    )
}

export default CookieStandAdmin


