import Head from 'next/head'
import CookieStandHeader from '../components/Header'
import CookieStandForm from '../components/Main'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  

      <CookieStandHeader/>
      
      <CookieStandForm />
      <Footer/>
    </div>
  )
}

